server:
  port: 8088
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 生成公钥和私钥的时候要加盐或者（secret）
    pubKeyPath: E:\\tmp_rsa\\rsa.pub
    priKeyPath: E:\\tmp_rsa\\rsa.pri
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 30