server:
  port: 8082
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///leyou
    username: believe
    password: believe
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时且没被使用就会被释放掉。缺省值：30分钟
      maximum-pool-size: 9  # 连接池中允许的最大连接数。缺省值：10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 发送心跳
    lease-expiration-duration-in-seconds: 10 # 10s过期