server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.164.128
eureka:
  client:
    service-url: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
